### PR TITLE
Fix relative imports, don't track .pyc files, help option i uploader etc

### PR DESCRIPTION
**Pull request by mattiasostmar**
It seems like one has to tamper with sys.path in Python 3 and I noticed that I was about to push a lot of .pyc files into the repo so I added them to .gitignore.

### CODE REVIEW

**Comment by mattiasostmar** [comment]
I've also added a clarification about the in_dir's expected contents to the file uploader.py

**Comment by mattiasostmar** [comment]
Även om du inte vill mergea nåt annat så tycker jag det är rimligt att en får en option för att se hjälptexten du skrivit i själva koden, men inte finns i terminalen ;-)

**Comment by lokal-profil** [comment]
I will cherry pick some of these into a new branch today or tomorrow.

Cherry picking since I don't believe they are all needed after some of the recent changes.

Once the branch is online you can try it via pip by appending `@branchname` to the url. I'll also try to debug further on toollabs.

**Comment by lokal-profil** [comment]
Would you mind trying out the `py3compat` branch?

**Pull request closed without merging**
